# Use postgres/example user/password credentials
version: '3.1'

services:

  api:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: /bin/sh -c "while sleep 1000; do :; done"

  db:
    image: postgres
    restart: always
    env_file: .env
    volumes:
      - "../data:/var/lib/postgresql/data"
    ports:
      - 5442:5432

  swagger:
    image: swaggerapi/swagger-ui
    env_file: .env
    volumes:
      - "../docs:/docs"
    ports:
      - 4040:8080
